# copyright (c) 2020 PaddlePaddle Authors. All Rights Reserve.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import paddle
from paddle import nn
import paddle.nn.functional as F
from paddle import ParamAttr

__all__ = ['MobileNetV3_MetaACON']


class MetaAconC(nn.Layer):
    r""" ACON activation (activate or not).
    # MetaAconC: (p1*x-p2*x) * sigmoid(beta*(p1*x-p2*x)) + p2*x, beta is generated by a small network
    # according to "Activate or Not: Learning Customized Activation" <https://arxiv.org/pdf/2009.04759.pdf>.
    """
    def __init__(self, width, r=8, name=None):
        super().__init__()
        # self.fc1 = nn.Conv2d(width, max(r, width // r), kernel_size=1, stride=1, bias=True)
        # self.bn1 = nn.BatchNorm2d(max(r, width // r))
        # self.fc2 = nn.Conv2d(max(r, width // r), width, kernel_size=1, stride=1, bias=True)
        # self.bn2 = nn.BatchNorm2d(width)

        self.fc1 = nn.Conv2D(
            in_channels=width, 
            out_channels=max(r, width // r),
            kernel_size=1,
            stride=1,
            bias_attr=ParamAttr(trainable=True))
        self.bn1 = nn.BatchNorm(
            num_channels=max(r, width // r),
            act=None,
            param_attr=ParamAttr(name=name + "_bn1_scale"),
            bias_attr=ParamAttr(name=name + "_bn1_offset"),
            moving_mean_name=name + "_bn1_mean",
            moving_variance_name=name + "_bn1_variance")
        self.fc2 = nn.Conv2D(
            in_channels=max(r, width // r), 
            out_channels=width,
            kernel_size=1,
            stride=1,
            bias_attr=ParamAttr(trainable=True))
        self.bn2 = nn.BatchNorm(
            num_channels=width,
            act=None,
            param_attr=ParamAttr(name=name + "_bn2_scale"),
            bias_attr=ParamAttr(name=name + "_bn2_offset"),
            moving_mean_name=name + "_bn2_mean",
            moving_variance_name=name + "_bn2_variance")

        # self.p1 = nn.Parameter(torch.randn(1, width, 1, 1))
        # self.p2 = nn.Parameter(torch.randn(1, width, 1, 1))
        self.p1 = paddle.static.create_parameter(
            shape=[1, width, 1, 1], 
            dtype='float32',
            name=name + '_acon_p1',
            default_initializer=nn.initializer.Normal(mean=0.0, std=1.0))
        self.p2 = paddle.static.create_parameter(
            shape=[1, width, 1, 1], 
            dtype='float32',
            name=name + '_acon_p2',
            default_initializer=nn.initializer.Normal(mean=0.0, std=1.0))

    def forward(self, x):
        beta = F.sigmoid(self.bn2(self.fc2(self.bn1(self.fc1(paddle.mean(paddle.mean(x, axis=2, keepdim=True), axis=3, keepdim=True))))))
        return (self.p1 * x - self.p2 * x) * F.sigmoid(beta * (self.p1 * x - self.p2 * x)) + self.p2 * x


def make_divisible(v, divisor=8, min_value=None):
    if min_value is None:
        min_value = divisor
    new_v = max(min_value, int(v + divisor / 2) // divisor * divisor)
    if new_v < 0.9 * v:
        new_v += divisor
    return new_v


class SEModule(nn.Layer):
    def __init__(self, in_channels, reduction=4, name=""):
        super(SEModule, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2D(1)
        self.conv1 = nn.Conv2D(
            in_channels=in_channels,
            out_channels=in_channels // reduction,
            kernel_size=1,
            stride=1,
            padding=0,
            weight_attr=ParamAttr(name=name + "_1_weights"),
            bias_attr=ParamAttr(name=name + "_1_offset"))
        self.conv2 = nn.Conv2D(
            in_channels=in_channels // reduction,
            out_channels=in_channels,
            kernel_size=1,
            stride=1,
            padding=0,
            weight_attr=ParamAttr(name + "_2_weights"),
            bias_attr=ParamAttr(name=name + "_2_offset"))

        self.act_func1 = MetaAconC(width=in_channels // reduction, r=8, name=name + '_acon1')
        self.act_func2 = MetaAconC(width=in_channels, r=8, name=name + '_acon2')

    def forward(self, inputs):
        outputs = self.avg_pool(inputs)
        outputs = self.conv1(outputs)
        # outputs = F.relu(outputs)
        outputs = self.act_func1(outputs)
        outputs = self.conv2(outputs)
        # outputs = F.hardsigmoid(outputs, slope=0.2, offset=0.5)
        outputs = self.act_func2(outputs)
        return inputs * outputs


class ConvBNLayer(nn.Layer):
    def __init__(self,
                 in_channels,
                 out_channels,
                 kernel_size,
                 stride,
                 padding,
                 groups=1,
                 if_act=True,
                 act=None,
                 name=None):
        super(ConvBNLayer, self).__init__()
        self.if_act = if_act
        self.act = act
        self.conv = nn.Conv2D(
            in_channels=in_channels,
            out_channels=out_channels,
            kernel_size=kernel_size,
            stride=stride,
            padding=padding,
            groups=groups,
            weight_attr=ParamAttr(name=name + '_weights'),
            bias_attr=False)

        self.bn = nn.BatchNorm(
            num_channels=out_channels,
            act=None,
            param_attr=ParamAttr(name=name + "_bn_scale"),
            bias_attr=ParamAttr(name=name + "_bn_offset"),
            moving_mean_name=name + "_bn_mean",
            moving_variance_name=name + "_bn_variance")

        self.act_func = MetaAconC(width=out_channels, r=8, name=name + '_acon')

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        if self.if_act:
            if self.act == "meta_acon":
                x = self.act_func(x)
            else:
                print("The activation function({}) is selected incorrectly.".
                      format(self.act))
                exit()
        return x


class ResidualUnit(nn.Layer):
    def __init__(self,
                 in_channels,
                 mid_channels,
                 out_channels,
                 kernel_size,
                 stride,
                 use_se,
                 act=None,
                 name=''):
        super(ResidualUnit, self).__init__()
        self.if_shortcut = stride == 1 and in_channels == out_channels
        self.if_se = use_se

        self.expand_conv = ConvBNLayer(
            in_channels=in_channels,
            out_channels=mid_channels,
            kernel_size=1,
            stride=1,
            padding=0,
            if_act=True,
            act=act,
            name=name + "_expand")
        self.bottleneck_conv = ConvBNLayer(
            in_channels=mid_channels,
            out_channels=mid_channels,
            kernel_size=kernel_size,
            stride=stride,
            padding=int((kernel_size - 1) // 2),
            groups=mid_channels,
            if_act=True,
            act=act,
            name=name + "_depthwise")
        if self.if_se:
            self.mid_se = SEModule(mid_channels, name=name + "_se")
        self.linear_conv = ConvBNLayer(
            in_channels=mid_channels,
            out_channels=out_channels,
            kernel_size=1,
            stride=1,
            padding=0,
            if_act=False,
            act=None,
            name=name + "_linear")

    def forward(self, inputs):
        x = self.expand_conv(inputs)
        x = self.bottleneck_conv(x)
        if self.if_se:
            x = self.mid_se(x)
        x = self.linear_conv(x)
        if self.if_shortcut:
            x = paddle.add(inputs, x)
        return x



class MobileNetV3_MetaACON(nn.Layer):
    def __init__(self,
                 in_channels=3,
                 model_name='small',
                 scale=0.5,
                 large_stride=None,
                 small_stride=None,
                 **kwargs):
        super(MobileNetV3_MetaACON, self).__init__()
        if small_stride is None:
            small_stride = [2, 2, 2, 2]
        if large_stride is None:
            large_stride = [1, 2, 2, 2]

        assert isinstance(large_stride, list), "large_stride type must " \
                                               "be list but got {}".format(type(large_stride))
        assert isinstance(small_stride, list), "small_stride type must " \
                                               "be list but got {}".format(type(small_stride))
        assert len(large_stride) == 4, "large_stride length must be " \
                                       "4 but got {}".format(len(large_stride))
        assert len(small_stride) == 4, "small_stride length must be " \
                                       "4 but got {}".format(len(small_stride))

        if model_name == "large":
            cfg = [
                # k, exp, c,  se,     nl,  s,
                [3, 16, 16, False, 'meta_acon', large_stride[0]],            # 1/2, 1/2
                [3, 64, 24, False, 'meta_acon', (large_stride[1], 1)],       # 1/4, 1/2
                [3, 72, 24, False, 'meta_acon', 1],
                [5, 72, 40, True, 'meta_acon', (large_stride[2], 1)],        # 1/8, 1/2
                [5, 120, 40, True, 'meta_acon', 1],
                [5, 120, 40, True, 'meta_acon', 1],
                [3, 240, 80, False, 'meta_acon', 1],
                [3, 200, 80, False, 'meta_acon', 1],
                [3, 184, 80, False, 'meta_acon', 1],
                [3, 184, 80, False, 'meta_acon', 1],
                [3, 480, 112, True, 'meta_acon', 1],
                [3, 672, 112, True, 'meta_acon', 1],
                [5, 672, 160, True, 'meta_acon', (large_stride[3], 1)],     # 1/16, 1/2
                [5, 960, 160, True, 'meta_acon', 1],
                [5, 960, 160, True, 'meta_acon', 1],
            ]
            cls_ch_squeeze = 960
        elif model_name == "small":
            cfg = [
                # k, exp, c,  se,     nl,  s,
                [3, 16, 16, True, 'meta_acon', (small_stride[0], 1)],
                [3, 72, 24, False, 'meta_acon', (small_stride[1], 1)],
                [3, 88, 24, False, 'meta_acon', 1],
                [5, 96, 40, True, 'meta_acon', (small_stride[2], 1)],
                [5, 240, 40, True, 'meta_acon', 1],
                [5, 240, 40, True, 'meta_acon', 1],
                [5, 120, 48, True, 'meta_acon', 1],
                [5, 144, 48, True, 'meta_acon', 1],
                [5, 288, 96, True, 'meta_acon', (small_stride[3], 1)],
                [5, 576, 96, True, 'meta_acon', 1],
                [5, 576, 96, True, 'meta_acon', 1],
            ]
            cls_ch_squeeze = 576
        else:
            raise NotImplementedError("mode[" + model_name + "_model] is not implemented!")

        supported_scale = [0.35, 0.5, 0.75, 1.0, 1.25]
        assert scale in supported_scale, \
            "supported scales are {} but input scale is {}".format(supported_scale, scale)

        inplanes = 16
        # conv1
        self.conv1 = ConvBNLayer(
            in_channels=in_channels,
            out_channels=make_divisible(inplanes * scale),
            kernel_size=3,
            stride=2,
            padding=1,
            groups=1,
            if_act=True,
            act='meta_acon',
            name='conv1')           # 1, 1/2
        i = 0
        block_list = []
        inplanes = make_divisible(inplanes * scale)
        for (k, exp, c, se, nl, s) in cfg:
            block_list.append(
                ResidualUnit(
                    in_channels=inplanes,
                    mid_channels=make_divisible(scale * exp),
                    out_channels=make_divisible(scale * c),
                    kernel_size=k,
                    stride=s,
                    use_se=se,
                    act=nl,
                    name='conv' + str(i + 2)))
            inplanes = make_divisible(scale * c)
            i += 1
        self.blocks = nn.Sequential(*block_list)

        self.conv2 = ConvBNLayer(
            in_channels=inplanes,
            out_channels=make_divisible(scale * cls_ch_squeeze),
            kernel_size=1,
            stride=1,
            padding=0,
            groups=1,
            if_act=True,
            act='meta_acon',
            name='conv_last')

        self.pool = nn.MaxPool2D(kernel_size=2, stride=2, padding=0)        # 1/32, 1/4
        self.out_channels = make_divisible(scale * cls_ch_squeeze)

    def forward(self, x):
        x = self.conv1(x)
        x = self.blocks(x)
        x = self.conv2(x)
        x = self.pool(x)
        return x
